example/main.js, example/package.json, index.js
Fixes https://github.com/maxogden/menubar/issues/30
=> Use app.getAppPath() as default path

index.js
=> Show window on all workspaces by default

index.js
As this problem now has been fixed in electron we should remove the fix.
Also fixed so `showWindow()` can be called without bounds being set. (Default to right).
See https://github.com/atom/electron/issues/1847#issuecomment-134098310
Closes #53
=> Remove temp-fix for getting clicked screen

index.js, readme.md
Hi everyone :-)
This PR provides an option to configure whether the dock icon should be hidden or not.
The `readme.md` was also updated.
Please let me know if this solution is suitable. Of course I'm open for ideas how to improve or change it.
This closes #62
=> Make dock icon visibility configurable #62

readme.md
Add some tips instead of increasing options
=> add some tips

index.js
=> update electron requires for v0.35.0

index.js, readme.md
=> Right click option

index.js
This is a fix for a bug that I introduced in #89. Sorry! :-)
=> use bounds from click event

index.js
With this change you can now use `mb.setOption(always-on-top, Boolean)` and it will dynamically change the behaviour of the window.
=> Dynamic `always-on-top` option

index.js
Checks if app.isReady, allowing menubar to be added at any point during runtime.
=> Support creation of menubar after app init

index.js, readme.md
[See comment](https://github.com/maxogden/menubar/pull/154#issuecomment-278132680) on PR #154
=> Rolled back PR #154, updated readme

readme.md
Use the electron package instead of electron-prebuilt which has been deprecated
=> Update electron package in README

src/Menubar.ts
=> fix: Fix double 'after-hide' event

.travis.yml, package.json
=> chore: Build on postinstall

README.md, examples/arrow/README.md, examples/hello-world/README.md, examples/native-menu/README.md
=> chore: Clearer READMEs

.travis.yml, examples/arrow/README.md, examples/hello-world/README.md, examples/native-menu/README.md, package.json, src/index.ts, src/util/getWindowPosition.ts
=> chore: Remove postinstall, export taskbarLocation

README.md
I noticed that relative link wasn't working. Hence, I changed to absolute link.
=> Correct the link

docs/README.md, docs/classes/_menubar_.menubar.md, docs/interfaces/_types_.options.md, docs/modules/_index_.md, docs/modules/_util_getwindowposition_.md, src/Menubar.ts, src/types.ts, src/util/cleanOptions.spec.ts, src/util/cleanOptions.ts
Resolves #262 
The code changes are small. I updated the tests and docs. There were more changes than expected when updating the docs. Maybe someone forgot to commit them before... or maybe I shouldn't be running the command?
=> Adding an indexLoadOptions option

.eslintignore, examples/package.json, examples/yarn.lock, package.json, yarn.lock
BREAKING CHANGE:
Menubar's recommended peer dependency is `electron@^8.0.0`
=> feat!: Support Electron 8

src/Menubar.ts
=> fix: update prevent flicker on Windows (fixes #274)

examples/arrow/main.js
https://github.com/maxogden/menubar/issues/295
=> fix: arrow example problem

WORKING_PLATFORMS.md
Tested it on my machine a few different ways and it works great!
Not sure what sorts of other tests you might need besides just playing with it and messing with the API to confirm, but it's solid from my end!
=> Add Windows 11 to working platforms

src/util/getWindowPosition.ts
if [this workaround is correct](https://github.com/max-mapper/menubar/issues/435#issuecomment-1581628798) then this should resolve https://github.com/max-mapper/menubar/issues/435 and https://github.com/gitify-app/gitify/issues/1162
=> fix: win32 launch position

.github/workflows/lint.yml, .github/workflows/test.yml
=> build: run workflows on master

README.md, biome.json, examples/arrow/index.css, package.json, yarn.lock
Add support for latest electron major version
=> chore: support electron 32.x.x
