index.js
Fixed the following with passed options:
- When including options, dir is assumed to be included
- width/height not applying to window initializer
=> Passed option bugfixes

index.js
If the resolution changes, the window is restored to the old position, which is no longer valid.
This pull request recalculates and sets the window position upon restore.
=> Deal with resolution change between window restore

index.js, readme.md
Which creates a `{show: false}` BrowserWindow on startup, decreasing load time on the first click of the Menubar itself.
Fairly noticeable on my macbook retina with any significant html/js being loaded.
I totally don't love the name `preCreateWindow`, ideas?
=> Add preCreateWindow option

index.js
FYI: First click is always a single click so there is no chance that the bounds won't already be populated (on OS X).
=> Listen for double-clicked event on tray. Fixes #21

index.js
* Allow `always-on-top` to be set.
* Could have added an option to overwrite the `blur` callback but that seemed like overkill
1. Set `always-on-top` to `true`
2. Open a menubar app
3. Ensure clicking on the icon continues to toggle the window state
4. Ensure clicking outside the app window keeps the window open
* https://github.com/maxogden/menubar/issues/26
=> Do not set blur event if "always-on-top" property is set

index.js
To reproduce this issue (on OSX at least)
```js
var menubar = require('menubar')
var mb = menubar()
mb.on('ready', function ready () {
console.log('app is ready')
mb.tray.setTitle('1234567')
})
```
=> window does not like non-integer pos, floor it

index.js, readme.md
[The readme says it's defaulted to `Icon.png`](https://github.com/maxogden/menubar#options) but it's actually set to `IconTemplate.png`.
:cat2:
=> Update default icon path to reflect readme

index.js
* Open the menubar app on the screen that was clicked, not always the focused one.
* Separate the workaround so it can easily be removed if/when electron fixes in core.
Open the menubar example app on separate displays with various configuration (vertically stacked, horizontally stacked) and make sure it always aligns properly
* https://github.com/maxogden/menubar/issues/19
* https://github.com/maxogden/menubar/pull/20
* https://github.com/atom/electron/issues/1847
* https://github.com/maxogden/menubar/issues/32
=> Always open menubar app on clicked screen

index.js, readme.md
Good to have when you need to set some option after the app is created. For instance when you have some logic that depends on electrons `screen` module which can't run before the app is ready.
=> Set and get options after menubar is created

index.js
The goal of this one line PR is to free key+click events (with Alt, Ctrl, Shift and "meta"), so that these can be used to show different menubars than the main one.
=> free key+click events for special cases

index.js
Adds `showWindow()` and `hideWindow()` to the menubar object. This is better than just running `mb.window.show()` as these functions trigger events and contains some nice logic.
This also fixes two other issues:
1. If you preload the window, `menubar.window` is now available on the ready event.
2. `opts.x` and `opts.y` can now be set to `0`.
:swimmer:
=> Make show/hide-window available outside

index.js, package.json, readme.md
This adds the option to position the window in common spots on the screen ([electron-positioner](https://github.com/jenslind/electron-positioner)). This also removes all screen positioning logic from `menubar`.
What do you think @fabien-d and @maxogden ?
Also, this needs testing on Windows!
Related: https://github.com/maxogden/menubar/pull/52
=> Use electron-positioner to position the window

index.js, readme.md
Following up #34 in light of https://github.com/muan/mojibar/pull/8 and https://github.com/maxogden/menubar/pull/34#commitcomment-12483477.
Mac icon names need to be suffixed with 'Template' to be treated as a Template, which would then adapt to OSX UI scheme(dark/light), therefore it makes more sense to have the default icon name be 'IconTemplate' than 'Icon'. Sorry for the back and forth. :pray: 
See http://git.io/vOlVE.
=> Change default icon name

index.js
Because: 
`(electron) loadUrl is deprecated. Use loadURL instead.` and `(electron) 'clicked' event is deprecated. Use 'click' event instead.`
=> remove deprecated things

index.js, readme.md
I had an issue whereby if I closed the menubar instance via cmd+w the menubar would become unrecoverable as the .window property was closed but the createWindow() function is not exported to replace.
The new functionality deletes the window property when 'close' is fired, when the showWindow() function is fired afterwards it will rebuild the window.
=> Cleaning up window when closed by hotkey

index.js
This allows showWindow to be called manually and the window will appear in the correct place assuming the tray has already been clicked at some stage.
My use case is that I want the tray to open on the `drop-files` event. Previous to this, calling `showWindow(null)` would position the window at the top-right (OS X). This is not an ideal solution because if the tray hasn't been clicked previously then the window will still appear in the top-right. A better solution could be implemented upstream in Electron (see: https://github.com/atom/electron/issues/3377).
This is a breaking change because it changes the behaviour of `menuBar.showWindow(null)` after the tray has been clicked.
This may not be a desirable PR for the reasons mentioned above but I'll submit it for reference anyway.
=> Move bounds cache to showWindow method

index.js
Closes #103
This feature was added to electron in 1.3.1: https://github.com/electron/electron/pull/6620
I've implemented it in a way that it doesn't break when used with earlier versions of electron.
=> Highlight the menubar icon when menubar window is visible

index.js
This is a follow-up to @CodeFusion's 977526535b709a34e6158f13bccde0bf8d2c05f5.
Electron does not allow creation of the tray object before app ready. However, if I create an app tray object in `app.on('ready' ...)`, then pass it into Menubar's constructor, still within app.ready
```
const mb = menubar({
dir: __dirname,
tray,
});
```
I receive exception
```
Uncaught Exception:
TypeError: Cannot set property 'tray' of undefined
at appReady (/Github/_project_/node_modules/menubar/index.js:53:18)
at create (/Github/_project_/node_modules/menubar/index.js:27:22)
```
due to `app` not yet being available to Menubar. This PR addresses that issue.
=> Fix app undefined when menubar created within app.ready

index.js
I found that using `app.hide()` instead of `BrowserWindow.hide()` solves focus problem on hiding menubar application.
https://github.com/electron/electron/blob/master/docs/api/browser-window.md
This should fix #153
=> Use app.hide() on macOS (fix #153)

index.js
[See comment](https://github.com/maxogden/menubar/pull/154#issuecomment-277887909) on PR #154. This fixes undesirable behavior on macOS when using multiple Electron windows.
=> Fix behavior for PR #154

CHANGELOG.md
When doing the port from the fork, discovered that the links in the CHANGELOG should point to issues on my own fork.
=> fix: Fix changelog links

package.json, src/index.ts
6.0.1 broke the fact that if no icon was provided, the default cat one was used. This PR fixes it.
=> fix: Fix bug default cat icon

example/package.json, example/yarn.lock
electron-prebuilt is retired, we now just use Electron 5 in the example
=> chore: Remove electron-prebuilt from example

src/Menubar.ts, src/util/getWindowPosition.ts
possibly supersedes #234 
fixes #233 
cc @pranit123 could you test this one? I tested on Windows 10, it works well
=> fix: Fix crash on windows position when tray on left/right

package.json
`typedoc` and `typedoc-plugin-markdown` are two tool to build doc, it is unnecessary for product.
Please move it to `devDependencies`(`npm` or `yarn` won't install it from any dependents)
Thank you for awesome module.
=> chore: move doc tool to `devDependencies`

.eslintignore, .eslintrc.js, .prettierrc.js, .travis.yml, README.md, package.json, src/Menubar.spec.ts, src/Menubar.ts, src/__mocks__/electron.ts, src/index.ts, src/util/cleanOptions.ts, src/util/getWindowPosition.ts, tsconfig.json, tslint.json, yarn.lock
Because the TypeScript team is officially going to support typescript-eslint.
=> chore: Use eslint instead of tslint

README.md, examples/package.json, examples/yarn.lock, package.json, src/Menubar.ts, src/index.ts, src/types.ts, src/util/cleanOptions.spec.ts, src/util/cleanOptions.ts, yarn.lock
fixes #243 
BREAKING CHANGE:
- Drop support for Electron 4, 5, and 6.
- Remove deprecated passing string argument to `menubar`, use `dir` field instead
```diff
- menubar('/home/me/MY_ABSOLUTE_PATH');
+ menubar({ dir: '/home/me/MY_ABSOLUTE_PATH' });
```
- Remove deprecated passing `x`, `y`, `height`, `width`, `alwaysOnTop` fields to `menubar`, pass them instead into the `browserWindow` field
```diff
- menubar({
-   x: 12,
-   y: 34,
-   height: 500,
-   width: 320,
-   alwaysOnTop: true
- });
+ menubar({
+   browserWindow: {
+     x: 12,
+     y: 34,
+     height: 500,
+     width: 320,
+     alwaysOnTop: true
+  }
+ });
```
=> feat!: Support Electron 7

docs/classes/_menubar_.menubar.md, docs/interfaces/_types_.options.md, docs/modules/_index_.md, docs/modules/_util_getwindowposition_.md, src/Menubar.ts, src/types.ts, src/util/cleanOptions.spec.ts, src/util/cleanOptions.ts
```typescript
const mb = menubar({ index: false });
```
will not call `browserWindow.loadUrl` internally at all. It will be the user's job to call that.
=> feat: Allow skipping loadUrl

src/Menubar.ts, src/__mocks__/electron.ts
=> Show window on dock icon click

src/Menubar.ts
This PR fixes the following bug: 
`this._isVisible` is only set to `true` in `clicked()` so if `showWindow()` is called directly, `this._isVisible` is not updated and prevents `closeWindow()` to work properly. 
```
const { menubar } = require('menubar');
const mb = menubar();
mb.on('ready', () => {
mb.showWindow();
});
```
The menubar window will show up but clicking outside would not close the window.
=> fix: calling showWindow() prevents menubar window from closing

src/Menubar.ts, src/util/getWindowPosition.ts
Should be helpful for the following issues
https://github.com/maxogden/menubar/issues/264
https://github.com/maxogden/menubar/issues/232
=> Improve 'windows' OS detection of taskbar location

src/Menubar.ts, src/util/getWindowPosition.ts
This PR fixes #123. Still, we can't get the tray bounds on Linux but, based on the `workArea` we can show it near to the tray. Tested it on Ubuntu & Linux Mint.
Also fixes the window positioning on Windows when the taskbar is on the left.
=> fix: window position on linux & windows when taskbar is on the left

README.md, examples/package.json, package.json, src/Menubar.ts, yarn.lock
With [`@electron/remote`](https://www.npmjs.com/package/@electron/remote) and Electron >= 14
we  must use the new enable API to enable the remote module for each desired WebContents separately: `require("@electron/remote/main").enable(webContents)`
The problem is that this enable function needs to be executed 
* after the BrowserWindow is created - (after `emit('create-window')`) 
* before `browserWindow.loadURL()` is called - (before `emit('after-create-window')`)
This new `before-load` event is perfect for this  (Tested and it fixes the problem)
Notes:
* from what I know, `@electron/remote` can't work without this PR, so would be great if this could be merged and a new hotfix version released @maxogden
* #366 tries to do the same thing but this PR keeps backward compatibility by …
=> add `before-load` event

src/Menubar.ts
Due to this code change https://github.com/electron/electron/pull/37599/files , `setVisibleOnAllWorkspaces(true)` has changed its original logic, resulting in the reappearance of the already hidden dockIcon. This change avoids the occurrence of this phenomenon
The affected versions include 23.2.x 24.x.x
=> fix: Avoid setVisibleOnAllWorkspaces from destroying the original visible state of app.dock

examples/native-menu/main.js
Hey Guys!
I've addressed the issue where the native menubar example was acting up. The problem was that clicking the icon in the menubar was opening both the native menu and the browser window, which wasn't the expected behavior. This seems to only happen on MacOS.
```javascript
mb.on('ready', () => {
console.log('Menubar app is ready.');
// Your app code here
tray.removeAllListeners(); // Removed unnecessary event listeners
});
```
I want to give credit where it's due: @Jip-Hop initially identified the issue and provided a workaround. Thanks to them for pointing it out! I've just created a pull request.
=> Fix for Broken Native Menubar Example

README.md, examples/package.json, examples/yarn.lock, package.json, yarn.lock
Closes https://github.com/max-mapper/menubar/issues/470
=> feat: widen electron support
